spring:
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 500
  h2:
    console:
      enabled: false
  flyway:
    enabled: false

logging:
  level:
    org.hibernate.SQL: info

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

    flyway:
      enabled: false

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://13.125.248.234:9000/cvi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: repl_master1
#    password: qorwnddnjs12!
#
#    slaves:
#      slave1:
#        name: slave1
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://15.164.21.185:9000/cvi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#        username: cvi
#        password: qorwnddnjs12!
#
#      slave2:
#        name: slave2
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://15.164.212.61:9000/cvi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#        username: cvi
#        password: qorwnddnjs12!
#
#      slave3:
#        name: slave3
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://13.124.85.26:9000/cvi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#        username: cvi
#        password: qorwnddnjs12!
#
#      slave4:
#        name: slave4
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://3.36.128.95:9000/cvi?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#        username: cvi
#        password: qorwnddnjs12!

#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        # show_sql: true
#        format_sql: true
#        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        jdbc:
#          lob:
#            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.hibernate.SQL: debug
